insert into tbuser(id, name, gender) values(0, 'Sunny Dach', 'F');
insert into tbuser(id, name, gender) values(1, 'Mrs. Axel Flatley', 'F');
insert into tbuser(id, name, gender) values(2, 'Trace Christiansen', 'F');
insert into tbuser(id, name, gender) values(3, 'Ervin Klein III', 'F');
insert into tbuser(id, name, gender) values(4, 'Jazmin Olson', 'F');
insert into tbuser(id, name, gender) values(5, 'Chaya OConner', 'F');
insert into tbuser(id, name, gender) values(6, 'Meda Romaguera Sr.', 'M');
insert into tbuser(id, name, gender) values(7, 'Mr. Delta Pagac', 'M');
insert into tbuser(id, name, gender) values(8, 'Aaron Krajcik', 'M');
insert into tbuser(id, name, gender) values(9, 'Donny Greenholt MD', 'M');
insert into tbuser(id, name, gender) values(10, 'Philip Lang', 'M');
insert into tbuser(id, name, gender) values(11, 'Barney Casper', 'M');
insert into tbuser(id, name, gender) values(12, 'Afton Lubowitz', 'M');
insert into tbuser(id, name, gender) values(13, 'Ms. Kyleigh Kuphal', 'M');
insert into tbuser(id, name, gender) values(14, 'Dana Kuhlman', 'M');
insert into tbuser(id, name, gender) values(15, 'Nelle Dooley PhD', 'M');
insert into tbuser(id, name, gender) values(16, 'Hazel Bosco', 'M');
insert into tbuser(id, name, gender) values(17, 'Evert Lynch DDS', 'M');
insert into tbuser(id, name, gender) values(18, 'Kaylah Kemmer', 'M');
insert into tbuser(id, name, gender) values(19, 'Lloyd Crooks', 'M');
